compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-12-3
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 100

iso_task:
  timeout_in: 120m
  script:
    - pkg-static install -y sshpass bash
    - ln -sf /usr/local/bin/bash /bin/bash
    - curl -Lo /tmp/version.txt https://raw.githubusercontent.com/mszoek/airyx/main/version.txt
    - cp -fv /tmp/version.txt overlays/ramdisk/version
    - AIRYX=/tmp VERSION=$(head -1 /tmp/version.txt) ./build.sh airyx airyxOS_${VERSION}
    - sshpass -e scp /usr/local/furybsd/iso/*.iso airyxos@dl.airyx.org:/var/www/html/nightly/
  only_if: $CIRRUS_BRANCH == 'main'
