compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-12-2
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 100

# Build all the packages, staying within the 2h task limit (hopefully)
ports_build_task:
  timeout_in: 120m
  environment:
    KEY: ENCRYPTED[f68765a53df76c1b9cd6d870e0054317f9cc517313bf6c56d0b094a1ad01e968a95e6328b37b53db7840d112ff165c46]
  ports_cache:
    folder: /usr/ports
    reupload_on_changes: false
    fingerprint_script: test -f /usr/ports/INDEX* && sha256 /usr/ports/INDEX* || true
    populate_script: make getports
  only_if: $CIRRUS_CHANGE_TITLE =~ '.*\[pkgs\].*' && $CIRRUS_BRANCH == 'main'
  script:
    - make prepports buildports makepackages
    - pkg install -y py37-pip
    - pip install --upgrade cloudsmith-cli
    - for p in /usr/ports/packages/*; do cloudsmith push raw -k $KEY airyx/core $p; done

# Build the FreeBSD kernel and patched toolchain 
base_build_task:
  timeout_in: 120m
  environment:
    KEY: ENCRYPTED[f68765a53df76c1b9cd6d870e0054317f9cc517313bf6c56d0b094a1ad01e968a95e6328b37b53db7840d112ff165c46]
  script:
    - pkg install -y git py37-pip
    - make prep freebsd packagesystem
    - pip install --upgrade cloudsmith-cli
    - cloudsmith push raw -k $KEY airyx/core freebsd-src/release/base.txz
    - cloudsmith push raw -k $KEY airyx/core freebsd-src/release/kernel.txz
  only_if: $CIRRUS_CHANGE_TITLE =~ '.*\[base\].*' && $CIRRUS_BRANCH == 'main'

# Build the Airyx system core
airyx_build_task:
  timeout_in: 120m
  environment:
    KEY: ENCRYPTED[f68765a53df76c1b9cd6d870e0054317f9cc517313bf6c56d0b094a1ad01e968a95e6328b37b53db7840d112ff165c46]
  script:
    - fetch -o /tmp/base.txz https://dl.cloudsmith.io/public/airyx/core/raw/files/base.txz
    - tar -C / -xvf /tmp/base.txz --exclude=./var/empty --exclude=./usr/lib --exclude=./sbin/init --exclude=./lib/libthr.so.3 --exclude=./libcrypt.so.5 --exclude=./lib/libc.so.7 --exclude=./libexec/ld-elf.so.1 --exclude=./usr/bin/crontab --exclude=./usr/bin/su --exclude=./usr/bin/opiepasswd --exclude=./usr/bin/passwd --exclude=./usr/bin/opieinfo --exclude=./usr/bin/login --exclude=./usr/bin/chpass --exclude=./usr/lib/librt.so.1
    - cp -afv mk/*.mk /usr/share/mk
    - cp -fv etc/pkg/*.conf /etc/pkg/ && rm -fv /etc/pkg/FreeBSD.conf
    - pkg install -y cmake jpeg-turbo openjpeg tiff png cairo fontconfig freetype2 libX11 libXext libXfixes libXdamage mesa-libs dbus pkgconf
    - make prep airyx airyx-package
  only_if: $CIRRUS_BRANCH == 'main'
  airyx_artifacts:
    path: freebsd-src/release/airyx.txz
